name: Linter
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        uses: actions/setup-node@v3
        with:
          node-version: 14
        run: npm ci
        run: npm test
      - name: install
        run: make install
      - name: ESLint test
        run: make lint
